enum CarType {
  Sedan
  Transporter
  Truck
}

enum CarMode {
  Moving
  Charging
  Parked
}

enum StationType {
  SixtStation
  ChargingStation
  Other
}

type User {
  name: String!
}

type Car {
  name: String!
  carType: CarType!
  maximumRange: Float!
  currentRange: Float!
  carMode: CarMode!
  lastTimeParked: Int!
  parkedAt: Station @relation
}

type Station {
  positionLat: Float!
  positionLong: Float!
  chargingSlots: Int!
  cars: [Car!] @relation
  stationType: StationType!
}

type Booking {
  car: Car!
  startDate: Int!
  endDate: Int!
  distance: Float!
  startStation: Station! @relation
  endStation: Station! @relation
}

type Query {
  allCars: [Car!]!
  allUsers: [User!]!
  allBookings: [Booking!]!
  allStations: [Station!]!
}
